alphabet = "abcdefghijklmnopqrstuvwxyz"

print("In:")
print("f" in alphabet)
print("F" in alphabet)
print("1" in alphabet)
print("ghi" in alphabet)
print("Xyz" in alphabet)
print("gfi" in alphabet)
print("Not In:")
print("f" not in alphabet)
print("F" not in alphabet)
print("1" not in alphabet)
print("ghi" not in alphabet)
print("Xyz" not in alphabet)
print("gfi" in alphabet)
