#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 16, 2025 06:04:31 PM %z  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import La_aplicacion_que_te_dice_MMG

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = La_aplicacion_que_te_dice_MMG.Toplevel(_top1)
    root.mainloop()

if __name__ == '__main__':
    La_aplicacion_que_te_dice_MMG.start_up()




